### ISSUE TITLE
Compute normals if not specified in OBJ file

### ISSUE THREAD

**Issue by declension** [declension/elm-obj-loader#5]
Currently OBJ files without vector normals fail parsing (and somewhat hard to debug this as the parser output isn't always easy to interpret)

Example: [this cow](https://groups.csail.mit.edu/graphics/classes/6.837/F03/models/cow-nonormals.obj).

I'm not sure how hard this is, but I imagine you can just take the right vectors, calculate the cross product and use that?

**Comment by Zinggi** [comment]
It's surprisingly difficult to calculate them properly, I don't think this package should do it.  

To do it properly, you would also have to respect the smooth groups. However, calculating normals inside a smooth group is also not easy and can in fact be done in several ways (e.g. how much weight do you give to a single surface?). In short, it adds a lot of complexity and I don't think it's worth it.

Also, the README explicitly mentions that this is not supported.

**Comment by declension** [comment]
I see, thanks for the info. I'll shut this then.
